#! /bin/sh -e

# Author: Mayur Singh
# Date: 19/2/16
# This is a shell script for Rahul Wadhwa (non-developer) to commit functionality on production server


if [ $1 ]
then
  cd ~/JetSetGo
  git status
  git add --all
  now=$(date +"%T")
  git commit -m "committed at $now"
  if ! [ $1 == master ]
  then
    git push origin $1
  else
    echo "Please use another branch"
  fi
else
  echo "No branch name specified."
  echo "Usage: commit_task <BRANCH NAME>"
fi
exit 0